apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-ms
  labels:
    app: config-server-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app : config-server-ms
  template:
    metadata:
      labels:
        app: config-server-ms
    spec:
      containers:
        - name: config-server-ms
          image: aminetb2a/config-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9296

---

kind: Service
apiVersion: v1
metadata:
  name:  config-server-svc
spec:
  selector:
    app:  config-server-ms
  ports:
    - port:  80
      targetPort:  9296


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-service-ms
  labels:
    app: zuul-service-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-service-ms
  template:
    metadata:
      labels:
        app: zuul-service-ms
    spec:
      containers:
        - name: zuul-service-ms
          image: aminetb2a/zuul-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8079

---

apiVersion: v1
kind: Service
metadata:
  name: zuul-service-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8079
      protocol: TCP
  selector:
    app: zuul-service-ms

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: aminetb2a/eureka-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address


---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: hystrix-dashboard-ms
  labels:
    app: hystrix-dashboard-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hystrix-dashboard-ms
  template:
    metadata:
      labels:
        app: hystrix-dashboard-ms
    spec:
      containers:
        - name: hystrix-dashboard-ms
          image: aminetb2a/hystrix-dashboard:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9295

---

apiVersion: v1
kind: Service
metadata:
  name: hystrix-dashboard-svc
spec:
  type: NodePort
  ports:
    - targetPort: 9295
      port: 80
  selector:
    app: hystrix-dashboard-ms

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server-ms
  labels:
    app: hello-server-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server-ms
  template:
    metadata:
      labels:
        app: hello-server-ms
    spec:
      containers:
        - name: hello-server-ms
          image: aminetb2a/hello-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8071

---

apiVersion: v1
kind: Service
metadata:
  name: hello-server-svc
spec:
  ports:
    - targetPort: 8071
      port: 80
  selector:
    app: hello-server-ms

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-client-ms
  labels:
    app: hello-client-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-client-ms
  template:
    metadata:
      labels:
        app: hello-client-ms
    spec:
      containers:
        - name: hello-client-ms
          image: aminetb2a/hello-client:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8072

---

apiVersion: v1
kind: Service
metadata:
  name: hello-client-svc
spec:
  ports:
    - targetPort: 8072
      port: 80
  selector:
    app: hello-client-ms
