spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aminetb2a/MicroserviceConfigFile
          clone-on-start: true

server:
  port: 9296

eureka:
  instance:
    hostname: eureka-0
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http//:eureka-0.eureka.default.svc.cluster.local:8761/eureka